export const products = [
  {
    sku: "SP-001",
    name: "Oil Filter",
    partNumber: "OF-1234",
    model: "S6R AYM",
    category: "Engine",
    brand: "Mitsubishi",
    stock: 25,
    unit: "PCS",
    cost: 150000,
    price: 220000,
    status: "Active",
  },
  {
    sku: "SP-002",
    name: "Air Filter",
    partNumber: "AF-5678",
    model: "S6R AYM",
    category: "Engine",
    brand: "Donaldson",
    stock: 12,
    unit: "PCS",
    cost: 200000,
    price: 300000,
    status: "Active",
  },
  {
    sku: "SP-003",
    name: "Fuel Pump",
    partNumber: "FP-7788",
    model: "S4K",
    category: "Fuel System",
    brand: "Denso",
    stock: 5,
    unit: "PCS",
    cost: 1250000,
    price: 1600000,
    status: "Active",
  },
  {
    sku: "SP-004",
    name: "Gasket Kit",
    partNumber: "GK-8899",
    model: "S6R AYM",
    category: "Engine",
    brand: "OEM",
    stock: 3,
    unit: "SET",
    cost: 850000,
    price: 1100000,
    status: "Low Stock",
  },
  {
    sku: "SP-005",
    name: "Radiator Hose",
    partNumber: "RH-3322",
    model: "S6R",
    category: "Cooling System",
    brand: "Gates",
    stock: 18,
    unit: "PCS",
    cost: 120000,
    price: 180000,
    status: "Active",
  },
  {
    sku: "SP-006",
    name: "Thermostat",
    partNumber: "TH-4455",
    model: "S4K",
    category: "Cooling System",
    brand: "Toyota",
    stock: 0,
    unit: "PCS",
    cost: 95000,
    price: 140000,
    status: "Out of Stock",
  },
  {
    sku: "SP-007",
    name: "Injector Nozzle",
    partNumber: "INJ-9900",
    model: "S6R AYM",
    category: "Fuel System",
    brand: "Bosch",
    stock: 9,
    unit: "PCS",
    cost: 450000,
    price: 600000,
    status: "Active",
  },
  {
    sku: "SP-008",
    name: "Cylinder Head",
    partNumber: "CH-1122",
    model: "S6R",
    category: "Engine",
    brand: "OEM",
    stock: 2,
    unit: "PCS",
    cost: 5500000,
    price: 7000000,
    status: "Low Stock",
  },
  {
    sku: "SP-009",
    name: "Starter Motor",
    partNumber: "SM-7788",
    model: "S4K",
    category: "Electrical",
    brand: "Hitachi",
    stock: 6,
    unit: "PCS",
    cost: 1750000,
    price: 2200000,
    status: "Active",
  },
  {
    sku: "SP-010",
    name: "Alternator",
    partNumber: "ALT-5566",
    model: "S6R AYM",
    category: "Electrical",
    brand: "Denso",
    stock: 4,
    unit: "PCS",
    cost: 2100000,
    price: 2600000,
    status: "Low Stock",
  },
];